### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by Temeteron** [balena-io-playground/balena-rpi-nodejs-basic-gpio#3]
Please add a docker file at this project and transform it to the format of your repo [simple-server-node](https://github.com/resin-io-projects/simple-server-node). Also, you could add a more detailed readme about each file and its purpose like in the basic tutorial.

It would be really helpful if you could transform all of your tutorials to one "format", so that everyone can integrate them to one bigger project.

**Comment by prichardsondev** [comment]
Funny I'm  getting started and was wondering where is the docker file which led me here. Wonder if we can push without one? I'm going to get this code working on a local pi [https://github.com/tutRPi/Raspberry-Pi-Simple-Web-GPIO-GUI] merge with the simpler-server-node example and try to push it. I'll let you know how it goes.

**Comment by dansku** [comment]
Done :)
