### ISSUE TITLE
Deployment fails

### ISSUE THREAD

**Issue by ajlennon** [balena-io-playground/balena-rpi-nodejs-basic-gpio#4]
Hi guys,

I'm using this based on the instructions in the Resin.io getting started guide.

The failure is due to a missing Python executable.

Moving from node-slim to node as the base image fixes it for me

Cheers.

**Comment by floion** [comment]
@nghiant2710 ^

**Comment by dansku** [comment]
@ajlennon sorry for the delay on this. 
I believe everything is working now, so I will close the issue. If it happens again please just open a new one.
